version: "3.8"

services:
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: metricvn
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    # depends_on:
    #   - postgres
    # environment:
    #   - DB_HOST=postgres
    #   - DB_PORT=5433
    #   - DB_USER=postgres
    #   - DB_PASS=postgres
    #   - DB_NAME=metricvn
    # volumes:
    #   - postgres:/var/lib/postgresql/data

# client:
#   build:
#     context: ./client
#     dockerfile: Dockerfile
#   environment:
#     - NUXT_PUBLIC_API_BASE_URL="http://localhost:8000/v1"
#     - NUXT_SERVER_API_BASE_URL="http://server:8000/v1"
#   ports:
#     - 3000:3000

volumes:
  postgres:
